- name: APT | Installation
  apt: name={{ item }}
  with_items:
    - apache2
    - apache2-utils
  when: ansible_pkg_mgr == "apt"

- name: APT | Installation of fcgid
  apt: name={{ item }}
  with_items:
    - libapache2-mod-fcgid
    - apache2-suexec-pristine
  when: ansible_pkg_mgr == "apt" and ( use_perl or use_fcgid )

- name: Enable common apache modules
  apache2_module: name={{ item }}
  with_items:
    - ssl
    - proxy
    - proxy_fcgi
    - rewrite
    - filter
    - deflate
    - headers

- name: Enable fcgid apache module
  apache2_module: name={{ items }}
  with_items:
    - cgid
    - fcgid
    - suexec
  when: use_perl or use_fcgid

- name: Enable default sites
  file: state={% if item.create %}link{% else %}absent{% endif %} src={{ item.src }} path={{ item.dest }}
  with_items:
    - src: /etc/apache2/sites-available/default-ssl.conf
      dest: /etc/apache2/sites-enabled/000-default-ssl.conf
      create: "{{ apache_use_default_ssl }}"
    - src: /etc/apache2/sites-available/000-default.conf
      dest: /etc/apache2/sites-enabled/000-default.conf
      create: "{{ apache_use_default }}"

- name: Disable mpm
  command: a2dismod mpm_{{ item }}
  register: a2dismod_output
  changed_when: "\"Module mpm_{{ item }} disabled.\" in a2dismod_output.stdout"
  when: "\"{{ item }}\" != \"{{ apache_mpm }}\""
  with_items:
    - prefork
    - event
    - worker

- name: Enable mpm
  command: a2enmod mpm_{{ apache_mpm }}
  register: a2enmod_output
  changed_when: "\"Enabling module mpm_{{ apache_mpm }}.\" in a2enmod_output.stdout"

- name: logrotate
  copy: src=vhost dest=/etc/logrotate.d/vhost owner=root group=root mode=0644

