- name: Fact | vhost_directory
  set_fact: vhost_directory=/var/www/{{ vhost_domain }}

- name: Fact | httpd etc
  set_fact: apache_etc=/etc/httpd

- name: Fact | apache sites-available
  set_fact: apache_sites_available={{ apache_etc }}/sites-available

- name: Fact | apache sites-enabled
  set_fact: apache_sites_enabled={{ apache_etc }}/sites-enabled

- name: Fact | apache sites-include
  set_fact: apache_sites_include={{ apache_etc }}/sites-include

- name: Fact | vhost_user_home
  set_fact: vhost_user_home={{ vhost_directory }}
  when: not vhost_user_home is defined

- name: Create site-include directory
  file: path={{ apache_sites_include }} owner=root group=root mode=0755 state=directory

- name: Ensure apache sites-available/sites-enabled exists
  file: path={{ item }} owner=root group=root mode=0755
  with_items:
    - "{{ apache_sites_enabled }}"
    - "{{ apache_sites_available }}"

- name: Create vhost directory
  file: path={{ vhost_directory }} owner=root group=root mode=0755 state=directory

- name: Ensure vhost_user_home exists
  file: path={{ vhost_user_home }} state=directory

- name: Create vhost user
  user: name={{ vhost_user }} createhome=no home={{ vhost_user_home }} shell={{vhost_user_shell}}

- name: Add apache to users group
  user: name=apache append=yes groups={{ vhost_user }}

- name: Create htdocs
  file: path={{ vhost_directory }}/htdocs owner={{ vhost_user }} group={{ vhost_user }} mode=0750 state=directory

- name: Create log directory
  file: path={{ vhost_directory }}/logs owner=root group={{ vhost_user }} mode=0750 state=directory

- name: Create tmp directory
  file: path={{ vhost_directory }}/tmp owner={{ vhost_user }} group={{ vhost_user }} mode=0700 state=directory

- name: Apache configuration
  template: src=vhost.conf.j2 dest={{ apache_sites_available }}/{{ vhost_domain }}.conf owner=root group=root mode=0644

- name: Enable Apache configuration
  file: state=link src={{ apache_sites_available }}/{{ vhost_domain }}.conf path={{ apache_sites_enabled }}/{{ vhost_domain }}.conf



